### ISSUE TITLE
feat: refactor form settings

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#37]
## Issue Overview

Because the countdown is so closely tied to the idea of the goal, and because closing the form happens with both the countdown and the goal, it's best to merge these together so there's not duplicating functions.

Additionally, we can reduce the total number of settings quite a bit by merging and making some smarter choices in which settings are available. 

## Current Behavior

Currently the Form Countdown has it's own tab with quite a few settings that have overlap with the goal and closing of the form. 

## Expected Behavior

I expect rather to have all the countdown options be together with the goal since it makes the most sense to think of them together. 

## Possible Solution

Hook into `give_after_donation_goal_options_settings` to output new countdown-specific settings.

We currently have all of these settings:
* Duration
* Timeframe
* Number of Days
* Countdown Clock
* End Message
* End Message Position

We could easily just add the following to the Donation Goal tab instead:

* Countdown Clock Enable/Disable
* Timeframe 
* Position

For Enable/Disable, let's make sure that can be chosen regardless of whether the Donation Goal is enabled or not. It's possible users might want a countdown with NO goal at all. 

I think timeframe should simply be the datepicker and time picker. We don't need the number of days option.

Position would simply be where within the form we want the Countdown to appear. 

For closing the form we can simply use inherit the existing Close Form options, including the messaging. 

## Todos
- [ ] Remove existing form settings tab
- [ ] Add the above two settings to the Goal tab
- [ ] refactor the frontend logic to look for the new settings

**Comment by mathetos** [comment]
Researching this a bit more, and asking the FB Community, it seems that there are enough use-cases for having a countdown independent of a Goal that we should not merge the two settings tabs. 

Instead, we'll refactor the existing form settings to include the following:

* Countdown Clock -- Enable/Disable
* Timeframe -- date/time picker
* Position -- Above amount, Below amount
* Theme -- Light, Dark, Custom See #39 -- "Custom" would open up a colorpicker field

**Comment by mathetos** [comment]
Additionally, we're going to completely separate the Goals settings from the Countdown settings. There's reasons why you would have both or either of them enabled/disabled and closed or not, so separate them and provide some options for a countdown closure message. 

So final list of Countdown settings is:

- [ ] Show Countdown -- Enable/Disable
- [ ] End Date -- Date Picker
- [ ] End Time -- Select field with times
- [ ] Clock Color Scheme -- Dark, Light, Custom
- [ ] Pick Your Custom Color -- Colorpicker (appears only when "Custom" is chose) 
- [ ] Closing Action -- None, Show Message, Show Message and Close Form
- [ ] End Message -- Text Editor (only appears if Closing Action is set to "Show Message" or "Show Message and Close Form".
