### ISSUE TITLE
feat: use FlipDown.js

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#38]
## Issue Overview

The existing JS library is old, a bit clunky and not maintained. FlipDown.js seems leaner and more mature. It's also plain vanilla JS, which feels like a better option going forward.

## Todos
- [x] Remove "The Final Countdown for jQuery"
- [x] Add FlipDown.js
- [x] Test as many different configurations as possible
