### ISSUE TITLE
feat: explore colors and themes

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#39]
## Issue Overview

The new FlipDown.js library supports "[themes](https://github.com/PButcher/flipdown#Themes)". We should consider the following:

1. Can we support using the Progress Bar color as the flip-card background color?
2. Should we just provide our own few custom themes in addition to "light" and "dark"?

## Todos
- [ ] Test using the Progress Bar color
- [ ] Test a nice gradient for the cards
- [ ] Consider the cost/benefit
- [ ] If it's worth it, build it out and close this issue.

**Comment by allienimmons** [comment]
Is there a way to set the color background of the countdown tiles with a HEX value? Like we have for the goal counter? I feel like being able to brand the counter would be a huge deciding factor for a lot of people so that it doesn't look out of place on the page.

**Comment by mathetos** [comment]
Ya, I'm considering "light", "dark" and "custom" where the default of custom would be whatever the progress bar color is already set to, but can be customized to whatever they want.

**Comment by mathetos** [comment]
Working with the built-in themes is very simple. The whole library is FAR simpler than the previous one and will be much easier to extend and customize. 

The light theme:
![image](https://user-images.githubusercontent.com/930724/77083236-6bb3cb00-69ba-11ea-892b-bc5995c61523.png)

Dark theme:
![image](https://user-images.githubusercontent.com/930724/77083279-7e2e0480-69ba-11ea-86bc-61def977d3cb.png)
