### ISSUE TITLE
Add shortcode and block options to [give_form] to show/hide countdown

### ISSUE THREAD

**Issue by mathetos** [impress-org/Give-Form-Countdown#48]
## Current Behavior
Form Countdown works great on single form pages. But if you embed it as a shortcode or a block you don't have any options to show/hide. That could be really useful.

## Expected Behavior

I expect to be able to show/hide the countdown when using the shortcode or block

## Related
User request:
https://www.facebook.com/groups/givewp/permalink/899597367169154/ 

## Todos
- [ ] Implement shortcode arg `countdown=show|hide` in [give_form] shortcode
- [ ] Confirm both show/hide work in the shortcode as intended
- [ ] Implement a toggle in the Give Form Gutenberg block to show/hide the countdown
